Repository vaadin/framework, pull requests merged in 2018-07, with the labels that each got.

#11034 Add xsrf token header if cookie is present
  client/src/main/java/com/vaadin/client/communication/Heartbeat.java
  client/src/main/java/com/vaadin/client/communication/XhrConnection.java
  server/src/main/resources/VAADIN/vaadinBootstrap.js
Labels: pick to 7

#11055 Ported change from 7.7 - ComboBox popup position while scrolling
  compatibility-client/src/main/java/com/vaadin/v7/client/ui/VFilterSelect.java
Labels: pick to compatibility package

#10743 Memory leak fix in ConnectorTracker
  server/src/main/java/com/vaadin/ui/ConnectorTracker.java
  server/src/main/java/com/vaadin/ui/Upload.java
Labels: v7

#11040 Add xsrf token header if cookie is present (#11034)
  client/src/main/java/com/vaadin/client/communication/Heartbeat.java
  client/src/main/java/com/vaadin/client/communication/XhrConnection.java
  server/src/main/resources/VAADIN/vaadinBootstrap.js
Labels: v7

#11047 Fix initially selected CheckBox rendering in Safari (#11024)
  client/src/main/java/com/vaadin/client/ui/VCheckBox.java
Labels: v7

#11074 Fix removal tabsheets if last one is selected
  client/src/main/java/com/vaadin/client/ui/VTabsheet.java
Labels: v7

#11078 Resolving the problem when editing in the grid editor is canceled and…
  client/src/main/java/com/vaadin/client/connectors/grid/EditorConnector.java
  uitest/src/main/java/com/vaadin/tests/components/grid/GridEditorEnableDisable.java
  uitest/src/test/java/com/vaadin/tests/components/grid/GridEditorEnableDisableTest.java
Labels: pick to 7

#11073 Fixed typo
  server/src/main/java/com/vaadin/data/util/AbstractInMemoryContainer.java
Labels: v7
