Repository vaadin/framework, pull requests merged in 2019-04, with the labels that each got.

#10999 Fixes a Grid issue that breaks sorting.
  client/src/main/java/com/vaadin/client/widgets/Grid.java
  uitest/src/main/java/com/vaadin/tests/widgetset/client/grid/GridBasicClientFeaturesWidget.java
  uitest/src/test/java/com/vaadin/tests/components/grid/basicfeatures/client/GridHeaderTest.java
Labels: pick to compatibility package, v7

#11523 setCaption of Panel did not honor setCaptionAsHtml
  client/src/main/java/com/vaadin/client/ui/VPanel.java
  client/src/main/java/com/vaadin/client/ui/panel/PanelConnector.java
  uitest/src/main/java/com/vaadin/tests/components/panel/PanelChangeContents.java
  uitest/src/main/java/com/vaadin/tests/components/panel/PanelHTMLCaption.java
  uitest/src/test/java/com/vaadin/tests/components/panel/PanelChangeContentsTest.java
  uitest/src/test/java/com/vaadin/tests/components/panel/PanelHTMLCaptionTest.java
Labels: pick to 7

#11506 Change VSlider to use Event.ONKEYDOWN with Firefox 65+
  client/src/main/java/com/vaadin/client/ui/VSlider.java
Labels: pick to compatibility package, v7

#11524 Fixing autocompletion issue with ComboBox on newer Chrome versions
  compatibility-client/src/main/java/com/vaadin/v7/client/ui/VFilterSelect.java
Labels: pick to compatibility package
